In [43]:
import tensorflow as tf

In [44]:
#To visualize the program with TensorBoard, we need to write log files of the program. 
#To write event files, we first need to create a writer for those logs, using this code:

#writer = tf.summary.FileWriter([logdir], [graph])

#[graph] is the graph of the program you are working on. You can either call it using tf.get_default_graph(), 
#which returns the default graph of the program, or through sess.graph,which returns the graph the session is handling.


In [45]:
a=tf.constant(2)
b=tf.constant(5)
c=tf.add(a,b)
writer=tf.summary.FileWriter("./graphs",tf.get_default_graph())
with tf.Session() as sess:
    print(sess.run(c))


7


In [46]:
var=tf.ones([2,3],name="constant_const",dtype=tf.int32)
with tf.Session() as sess:
    print(sess.run(var))
    print("\n")
    print(sess.run(tf.zeros_like(var))) #similarly tf.ones_like
    print("\n")
    print(sess.run(tf.fill((1,2),8)))   # tf.fill is to fill matrix with a number here it is 8
    print("\n")
    print(sess.run(tf.lin_space(1.0,5.0,5)))#linear spaced :np.linspace.Note that tensor objects are not iterable unlike numpy 
    print("\n")
    print(sess.run(tf.range(start=10,limit=20,delta=2,dtype=tf.int32)))
    print("\n")
    #tf.random_normal,tf.truncated_normal,tf.random_uniform,tf.random_shuffle,tf.random_crop,tf.multinomial,tf.random_gamma,tf.set_random_seed
    
    

[[1 1 1]
 [1 1 1]]


[[0 0 0]
 [0 0 0]]


[[8 8]]


[1. 2. 3. 4. 5.]


[10 12 14 16 18]




In [48]:
a=tf.constant([[1,2,3],[4,5,6]])
b=tf.constant([[4,5,6],[4,5,6]])

In [50]:
with tf.Session() as sess:
    print(sess.run(tf.div(b,a)))
    print("\n")
    print(sess.run(tf.divide(b,a)))

[[4 2 2]
 [1 1 1]]


[[4.  2.5 2. ]
 [1.  1.  1. ]]


In [51]:
#tf.add_n Allows you to add multiple tensors.
#tf.add_n([a, b, b])  => equivalent to a + b + b


In [59]:
with tf.Session() as sess:
    print(sess.run(tf.add_n([4,5,6,7,8,])))

30


In [74]:
a = tf.constant([10, 20], name='a')
b = tf.constant([2, 3], name='b')
c=tf.constant([[2,2],[2,1]])
d=tf.constant([[2,1],[1,2]])
with tf.Session() as sess:
    print(sess.run(tf.multiply(a, b)))
    print("\n")
    print(sess.run(tf.tensordot(a, b, 0)))
    print("\n")
    print(sess.run(tf.matmul(c, d)))
 
    

[20 60]


[[20 30]
 [40 60]]


[[6 6]
 [5 4]]


In [ ]:
#to see graph definition in tensorflow 
print(tf.get_default_graph().as_graph_def())

In [78]:
#tf.Variable ops

#x = tf.Variable(...) 
#x.initializer # init 
#x.value() # read op 
#x.assign(...) # write op 
#x.assign_add(...) 
# and more


In [83]:
#Example first
first_tf_get_variable = tf.get_variable("matrix", initializer=tf.Variable([[0, 1], [2, 3]]))

In [92]:
#Example second
second_tf_get_variable = tf.get_variable("vari", initializer=tf.random_uniform(shape=[2,3]))

In [98]:
#Example Third
W = tf.get_variable("big_mtrix", shape=(784, 10), initializer=tf.zeros_initializer())


In [99]:
#To get a list of uninitialized variables, you can just print them out:
with tf.Session() as sess:
    print(sess.run(tf.report_uninitialized_variables()))


[b'Variable' b'matrix' b'var' b'vari' b'big_matrix' b'big_matrixx'
 b'big_mtrix']


In [100]:
init_op=tf.global_variables_initializer()

In [101]:
with tf.Session() as sess:
    sess.run(init_op)
    print(sess.run(tf.report_uninitialized_variables()))

[]


In [103]:
#To initialize only a subset of variables, you use tf.variables_initializer() with a list of variables you want to initialize
new_var=tf.get_variable(name="new",shape=(2,2),initializer=tf.zeros_initializer())


In [106]:
with tf.Session() as sess:
    print(sess.run(tf.report_uninitialized_variables()))
    sess.run(tf.variables_initializer([new_var,first_tf_get_variable,second_tf_get_variable]))
    print(sess.run(tf.report_uninitialized_variables()))

[b'Variable' b'matrix' b'var' b'vari' b'big_matrix' b'big_matrixx'
 b'big_mtrix' b'new']
[b'Variable' b'var' b'big_matrix' b'big_matrixx' b'big_mtrix']
