In [43]:
import tensorflow as tf

In [44]:
#To visualize the program with TensorBoard, we need to write log files of the program. 
#To write event files, we first need to create a writer for those logs, using this code:

#writer = tf.summary.FileWriter([logdir], [graph])

#[graph] is the graph of the program you are working on. You can either call it using tf.get_default_graph(), 
#which returns the default graph of the program, or through sess.graph,which returns the graph the session is handling.


In [45]:
a=tf.constant(2)
b=tf.constant(5)
c=tf.add(a,b)
writer=tf.summary.FileWriter("./graphs",tf.get_default_graph())
with tf.Session() as sess:
    print(sess.run(c))


7


In [46]:
var=tf.ones([2,3],name="constant_const",dtype=tf.int32)
with tf.Session() as sess:
    print(sess.run(var))
    print("\n")
    print(sess.run(tf.zeros_like(var))) #similarly tf.ones_like
    print("\n")
    print(sess.run(tf.fill((1,2),8)))   # tf.fill is to fill matrix with a number here it is 8
    print("\n")
    print(sess.run(tf.lin_space(1.0,5.0,5)))#linear spaced :np.linspace.Note that tensor objects are not iterable unlike numpy 
    print("\n")
    print(sess.run(tf.range(start=10,limit=20,delta=2,dtype=tf.int32)))
    print("\n")
    #tf.random_normal,tf.truncated_normal,tf.random_uniform,tf.random_shuffle,tf.random_crop,tf.multinomial,tf.random_gamma,tf.set_random_seed
    
    

[[1 1 1]
 [1 1 1]]


[[0 0 0]
 [0 0 0]]


[[8 8]]


[1. 2. 3. 4. 5.]


[10 12 14 16 18]




In [48]:
a=tf.constant([[1,2,3],[4,5,6]])
b=tf.constant([[4,5,6],[4,5,6]])

In [50]:
with tf.Session() as sess:
    print(sess.run(tf.div(b,a)))
    print("\n")
    print(sess.run(tf.divide(b,a)))

[[4 2 2]
 [1 1 1]]


[[4.  2.5 2. ]
 [1.  1.  1. ]]


In [51]:
#tf.add_n Allows you to add multiple tensors.
#tf.add_n([a, b, b])  => equivalent to a + b + b


In [59]:
with tf.Session() as sess:
    print(sess.run(tf.add_n([4,5,6,7,8,])))

30


In [74]:
a = tf.constant([10, 20], name='a')
b = tf.constant([2, 3], name='b')
c=tf.constant([[2,2],[2,1]])
d=tf.constant([[2,1],[1,2]])
with tf.Session() as sess:
    print(sess.run(tf.multiply(a, b)))
    print("\n")
    print(sess.run(tf.tensordot(a, b, 0)))
    print("\n")
    print(sess.run(tf.matmul(c, d)))
 
    

[20 60]


[[20 30]
 [40 60]]


[[6 6]
 [5 4]]


In [ ]:
#to see graph definition in tensorflow 
print(tf.get_default_graph().as_graph_def())

In [78]:
#tf.Variable ops

#x = tf.Variable(...) 
#x.initializer # init 
#x.value() # read op 
#x.assign(...) # write op 
#x.assign_add(...) 
# and more


In [83]:
#Example first
first_tf_get_variable = tf.get_variable("matrix", initializer=tf.Variable([[0, 1], [2, 3]]))

In [92]:
#Example second
second_tf_get_variable = tf.get_variable("vari", initializer=tf.random_uniform(shape=[2,3]))

In [98]:
#Example Third
W = tf.get_variable("big_mtrix", shape=(784, 10), initializer=tf.zeros_initializer())


In [99]:
#To get a list of uninitialized variables, you can just print them out:
with tf.Session() as sess:
    print(sess.run(tf.report_uninitialized_variables()))


[b'Variable' b'matrix' b'var' b'vari' b'big_matrix' b'big_matrixx'
 b'big_mtrix']


In [100]:
init_op=tf.global_variables_initializer()

In [101]:
with tf.Session() as sess:
    sess.run(init_op)
    print(sess.run(tf.report_uninitialized_variables()))

[]


In [103]:
#To initialize only a subset of variables, you use tf.variables_initializer() with a list of variables you want to initialize
new_var=tf.get_variable(name="new",shape=(2,2),initializer=tf.zeros_initializer())


In [106]:
with tf.Session() as sess:
    print(sess.run(tf.report_uninitialized_variables()))
    sess.run(tf.variables_initializer([new_var,first_tf_get_variable,second_tf_get_variable]))
    print(sess.run(tf.report_uninitialized_variables()))

[b'Variable' b'matrix' b'var' b'vari' b'big_matrix' b'big_matrixx'
 b'big_mtrix' b'new']
[b'Variable' b'var' b'big_matrix' b'big_matrixx' b'big_mtrix']


In [107]:
#We can also initialize each variable separately using tf.Variable.initializer
#with tf.Session() as sess:
#    sess.run(W.initializer)


In [108]:
V = tf.get_variable("normal_matrix", shape=(784, 10), initializer=tf.random_uniform_initializer())

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(V))


[[0.01564419 0.07106733 0.80666053 ... 0.47924352 0.97808087 0.02599919]
 [0.52810717 0.93668973 0.46536958 ... 0.8735168  0.65683794 0.2373724 ]
 [0.62644875 0.16724753 0.18982446 ... 0.30773675 0.10423744 0.35893643]
 ...
 [0.7441596  0.17312956 0.02256322 ... 0.5300069  0.38365793 0.76768935]
 [0.45346284 0.06405807 0.0785979  ... 0.49552143 0.21325457 0.7857413 ]
 [0.98488307 0.97198486 0.32325947 ... 0.94202924 0.3384341  0.69374466]]


In [110]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(V.eval()) #can be used 


[[0.36406457 0.44060302 0.45653558 ... 0.5190283  0.2931583  0.60079753]
 [0.6549885  0.05518162 0.83674586 ... 0.43239033 0.15312624 0.02872181]
 [0.6693021  0.38864017 0.5763912  ... 0.9044485  0.47503376 0.8031801 ]
 ...
 [0.68565536 0.35188198 0.16196132 ... 0.3901304  0.14641225 0.22309864]
 [0.69625795 0.989288   0.81727004 ... 0.4551158  0.18005717 0.2927742 ]
 [0.54394424 0.3429377  0.21290302 ... 0.825014   0.39532375 0.20259047]]


In [111]:
#Assign value to variables


W = tf.Variable(10)
W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    print(W.eval()) 


10


In [112]:
# W.assign(100) doesn't assign the value 100 to W, but instead create an assign op to do that.
#For this op to take effect, we have to run this op in session. 

In [113]:
W = tf.Variable(10)

assign_op = W.assign(100)
with tf.Session() as sess:
    sess.run(assign_op)
    print(W.eval()) 

100


In [116]:
#When we have a variable that depends on another variable, suppose we want to declare U = W *2

W = tf.Variable(tf.truncated_normal([700, 10]))
U = tf.Variable(W * 2)

U = tf.Variable(W.initialized_value()* 2)


In [117]:
#Interactive Session

In [122]:
sess = tf.InteractiveSession()


In [123]:
a = tf.constant(3)
b = tf.constant(5)
c = a * b


In [124]:
print(c.eval()) 



15


In [125]:
sess.close()

In [127]:
#tf.get_default_session() returns the default session for the current thread. The returned Session will be the innermost 
#session on which a Session or Session.as_default() context has been entered.

In [131]:
#Control Dependencies

In [132]:
#Sometimes, we have two or more independent ops and we'd like to specify which ops should be run first. 
#In this case, we use tf.Graph.control_dependencies([control_inputs]).

In [135]:
# our graph g have 5 ops: a, b, c, d, e
#with g.control_dependencies([a, b, c]):
  # `d` and `e` will only run after `a`, `b`, and `c` have executed.
  #d = ...
  #e = …


In [165]:
a=tf.placeholder(tf.int32,shape=(5),name="first")

In [166]:
b=tf.constant([8,7,6,5,4])

In [167]:
c=tf.add(a,b)

In [168]:
with tf.Session() as sess:
    print(sess.run(c,feed_dict={a:[1,2,3,4,5]}))

[9 9 9 9 9]


In [169]:
# To check if a tensor is feedable or not, use:

#tf.Graph.is_feedable(tensor)
