In [56]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'1.8.0'

In [4]:
#fill with a random value

fill_random=tf.fill((4,4),10)

In [7]:
#ones

one_ran=tf.ones((4,4))

#zeros

zeros_ran=tf.zeros((4,4))

#normal gausian distribution

gaussian_normal=tf.random_normal((4,4))

#uniform distribution

uniform_normal=tf.random_uniform((4,4))

ops=[fill_random,one_ran,zeros_ran,gaussian_normal,uniform_normal]



In [9]:
with tf.Session() as sess:
    for op in ops:
        print(sess.run(op))
        print("\n")

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[-1.4333189  -1.471618    1.4467049  -0.01437237]
 [-0.03739963  0.51683885 -1.3999336  -1.889348  ]
 [-0.35175067  1.5117584  -0.7044044  -0.16642357]
 [-0.2943137   0.3556056  -1.0796146  -1.2500054 ]]


[[0.9032072  0.73184454 0.55531955 0.9545002 ]
 [0.23525369 0.5102701  0.8696667  0.4816271 ]
 [0.2920977  0.88818717 0.6867908  0.18865263]
 [0.52535534 0.17194688 0.11780202 0.699252  ]]




In [10]:
a=tf.constant([[1,2,3],
               [4,5,6]])

In [16]:
print(a.shape)
print(a.get_shape())



(2, 3)
(2, 3)


In [22]:
#graph

g_default=tf.get_default_graph()
print(g)
g_new=tf.Graph()
print(g_new)

In [25]:
with g_new.as_default():
    print(g_new is tf.get_default_graph())

True


In [26]:
print(g_new is tf.get_default_graph())

False


In [27]:
#tensorflow variables
var=tf.random_uniform((4,4),0,15)

In [28]:
variable_t=tf.Variable(initial_value=var)
op=tf.global_variables_initializer()


In [34]:
with tf.Session() as sess:
    sess.run(op)
    result=sess.run(variable_t)

In [35]:
print(result)

[[14.524196    2.8350072  13.183545    6.8335924 ]
 [ 4.203018    5.7560277  13.759436   10.8150835 ]
 [ 5.4362764   7.424855    2.3039265   6.3284006 ]
 [ 0.61958134  9.06031    14.137271    7.927333  ]]


In [37]:
#tensorflow placeholder

place_holder=tf.placeholder(tf.float32,shape=(None,5))

In [40]:
place_holder.get_shape()

TensorShape([Dimension(None), Dimension(5)])

In [ ]:
#seeding


np.random.seed(10)
tf.random_seed(10)


In [68]:
rand_a=np.random.uniform(0,5,(4,4))
rand_b=np.random.uniform(0,4,(4,1))

print(rand_a)
print("\n")
print(rand_b)


[[3.35262882 0.63529518 2.89688038 0.573614  ]
 [0.17457957 3.85794032 0.5627701  0.47606134]
 [2.00689923 2.34545504 0.19149147 2.87451987]
 [4.68749788 3.414414   0.84837823 1.86304018]]


[[0.42784325]
 [2.84783003]
 [0.48289813]
 [0.2969771 ]]


In [69]:
pf_a=tf.placeholder(tf.float32)
pf_b=tf.placeholder(tf.float32)


In [70]:
add_op=pf_a+pf_b

In [71]:
with tf.Session() as sess:
    result=sess.run(add_op,feed_dict={pf_a:rand_a,pf_b:rand_b}) #in feed_dict tensors can't be passed so pass numpy array

In [72]:
print(result)

[[3.780472  1.0631384 3.3247237 1.0014572]
 [3.0224097 6.7057705 3.4106002 3.3238914]
 [2.489797  2.828353  0.6743896 3.357418 ]
 [4.984475  3.711391  1.1453553 2.1600173]]
